import duckdb

con = duckdb.connect()

print("\n === === === === Volume distribution === === === ===\n")
con.sql("""
COPY (
WITH CHECK123 AS (
    SELECT CASE WHEN ticker ILIKE '%KXMVESPORTSMULTIGAMEEXTENDED%' THEN 'Parlay'
                WHEN ticker ILIKE '%NCAA%' THEN 'NCAA'
                WHEN ticker ILIKE '%KXHEISMAN%' THEN 'NCAA'
                WHEN ticker ILIKE '%KXPSUCOACH%' THEN 'NCAA'
                WHEN ticker ILIKE '%KXLSUCOACH%' THEN 'NCAA'
                WHEN ticker ILIKE '%KXGAMEDAYMENTION%' THEN 'NCAA'
                WHEN ticker ILIKE '%NFL%' THEN 'NFL'
                WHEN ticker ILIKE '%KXAFCONGAME%' THEN 'NFL'
                WHEN ticker ILIKE '%KXAFC%' THEN 'NFL'
                WHEN ticker ILIKE '%KXNFC%' THEN 'NFL'
                WHEN ticker ILIKE '%KXTRUMPFOOTBALL%' THEN 'NFL'
                WHEN ticker ILIKE '%KXSB%' THEN 'SuperBowl'
                WHEN ticker ILIKE '%SUPERBOWL%' THEN 'SuperBowl'
                WHEN ticker ILIKE '%KXTEAMSINSB%' THEN 'SuperBowl'
                WHEN ticker ILIKE '%NBA%' THEN 'NBA'
                WHEN ticker ILIKE '%BOXING%' THEN 'BOXING'
                WHEN ticker ILIKE '%KXUFCFIGHT%' THEN 'UFC'
                WHEN ticker ILIKE '%KXUFCMOV%' THEN 'UFC'
                WHEN ticker ILIKE '%KXUFCROUNDS%' THEN 'UFC'
                WHEN ticker ILIKE '%NHL%' THEN 'NHL'
                WHEN ticker ILIKE '%MLB%' THEN 'MLB'
                WHEN ticker ILIKE '%KXMARMAD%' THEN 'March Madness'
                WHEN ticker ILIKE '%KXWMARMAD%' THEN 'March Madness'
                WHEN ticker ILIKE '%KXWMENSINGLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXWTAMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXUSOPEN%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXUSOWOMENSINGLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXUSOMENSINGLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXFOMENSINGLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXWWOMENSINGLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXATPMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXFOMEN%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXAOMEN%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXDAVISCUPMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXATPDOUBLES%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXATPCHALLENGERMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXWTACHALLENGERMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXATPEXACTMATCH%' THEN 'Tennis'
                WHEN ticker ILIKE '%KXMASTERS%' THEN 'Golf'
                WHEN ticker ILIKE '%KXTHEOPEN%' THEN 'Golf'
                WHEN ticker ILIKE '%KXLIVTOUR%' THEN 'Golf'
                WHEN ticker ILIKE '%KXTGLMATCH%' THEN 'Golf'
                WHEN ticker ILIKE '%KXPGA%' THEN 'Golf'
                WHEN ticker ILIKE '%KXPREMIERLEAGUE%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXDENSUPERLIGAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEKSTRAKLASAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSCOTTISHPREMGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSWISSLEAGUEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXHNLGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXKNVBCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXUECLGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXARGPREMDIVGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXBELGIANPLGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXDFBPOKALGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXJLEAGUEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXINTLFRIENDLYGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXFRASUPERCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXCOUPEDEFRANCEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXCOPPAITALIAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXLIGAPORTUGALGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXTACAPORTGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSUPERLIGGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEPL%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXUEFACL%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXESPSUPERCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXINTERCONCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSAUDIPLGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXLALIGAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEUROLEAGUEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXLIGUE1GAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXBUNDESLIGAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXKNVBCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXFACUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXCLUBWCGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSERIEAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEFLCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXFIFAGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEFLCHAMPIONSHIPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXCOPADELREYGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXMLSGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEUROCUPGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXUNITEDCUPMATCH%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXLIGAMXGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXUCL%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXBRASILEIROGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXSLGREECEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXEREDIVISIEGAME%' THEN 'Soccer'
                WHEN ticker ILIKE '%KXDOTA2GAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXCODGAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXUELGAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXCSGOGAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXLEAGUEWORLDS%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXVALORANTGAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXLOLGAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXLOLMAP%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXCS2GAME%' THEN 'E-Sports'
                WHEN ticker ILIKE '%KXFOWOMENSINGLES%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXINDY500%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXF1%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXMENWORLDCUP%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXNBLGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXALEAGUEGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXKBLGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%COACH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%HOCKEY%' THEN 'Other Sports'
                WHEN ticker ILIKE '%CURL%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXWO-GOLD-26%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXT20MATCH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXT20WORLDCUP%' THEN 'Other Sports'
                WHEN ticker ILIKE '%CHESS%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXCRICKETT20IMATCH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXNASCAR%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXFIBACHAMPLEAGUEGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXCBAGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXLNBELITEGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXJBLEAGUEGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXFIBAECUPGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXBSLGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXSIXNATIONSMATCH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXCRICKETTESTMATCH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXCRICKETODIMATCH%' THEN 'Other Sports'
                WHEN ticker ILIKE '%REESKI%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXBBLGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXABAGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXVTBGAME%' THEN 'Other Sports'
                WHEN ticker ILIKE '%KXWPLGAME%' THEN 'Other Sports'
                ELSE 'LIKELY NOT SPORTS' END AS MKT_TYPE
        , SUM(count) as Total_Volume  
    FROM '/Users/iamsam/WorkingFiles/PredictionMarkets/Kalshi/summaryStats/kalshi_trades.parquet'
    GROUP BY 1
    ORDER BY Total_Volume DESC
),
                      
TotalVolumeAllMarkets AS (
    SELECT SUM(count) as NET_TOTAL_VOLUME
    FROM '/Users/iamsam/WorkingFiles/PredictionMarkets/Kalshi/summaryStats/kalshi_trades.parquet'
)
                      
SELECT C.MKT_TYPE as Market_Type
     , C.Total_Volume::DECIMAL AS Total_Volume
     , ROUND((C.Total_Volume::FLOAT / T.NET_TOTAL_VOLUME)*100, 2)::VARCHAR || '%' AS Volume_PCT
FROM CHECK123 C
    LEFT JOIN TotalVolumeAllMarkets T ON 1=1
) TO sports_data.csv (HEADER, DELIMITER ',');    
""")